fixtures:
  symlinks:
    sasl: "#{source_dir}"
  forge_modules:
    bodgitlib:
      repo: "bodgit/bodgitlib"
      ref: "2.0.1"
    ip:
      repo: "thrnio/ip"
      ref: "1.0.1"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.25.1"
